### ISSUE TITLE
Crashing on recent window after updating AOSP a13 qpr

### ISSUE THREAD

**Issue by waseemafzal70** [Kingsman44/Pixelify#154]
I was using pixelify on AOSP 13 November security patch and it was working fine but when I updated my rom to a13 qpr December security patch it starts crashing on recent tabs. I tried to disable suggestions on recent windows but it didn't work for me. Is there any hope in next pixelify update?

**Comment by Kingsman44** [comment]
Yes, it will be fixed but it gonna take some time as i dont have access to december patch roms

**Comment by waseemafzal70** [comment]
Okay thanks, I'll be waiting for the fix.

**Comment by khaled-0** [comment]
+1 waiting

**Comment by waseemafzal70** [comment]
> +1 waiting

There is a new release 2.2 beta 3, the problem is fixed in new update

**Comment by khaled-0** [comment]
Well not for me
On v2.2 beta 3

Pixel launcher still crashing on Recent Screen
Evolution X December patch.
My rom had pixel launcher built in but
Rom maintainer replaced Pixel launcher with their own launcher.
Now even Pixelify can't make Pixel Launcher App Switcher work
Crash logs: https://paste.evolution-x.org/NEMOyM
Rom commit logs: https://evolution-x.org/device/veux

**Comment by khaled-0** [comment]
@Kingsman44 I've sent those reports on the telegram channel but they got piled up.
Can you please check it if you're not busy.

**Comment by khaled-0** [comment]
> Pixel launcher extended.

Still same
Crashes on recent
maybe it's got to do something with the rom
