### ISSUE TITLE
Google photos phone too hot

### ISSUE THREAD

**Issue by gerardovasquez307** [Kingsman44/Pixelify#47]
With this and many previous versions of Pixelify, I have never been able to backup with unlimited original quality. The note phone is too hot remains on always and never let's me backup. Phone does not have this issue on unlimited storage saver. Oneplus 9 on latest oxygen os 11 and latest Pixelify.

**Comment by Rihcus** [comment]
I'm not to sure why your phone is hot but I can confirm the unlimited original quality photos not working. I was only able to notice today once seeing googles storage saver recommending me to delete blurry photos and then testing by uploing a 1gb dummy video recorded on my one plus 8. I'm unsure if this is because pixelify used a pixel 3XL to spoof unlimited original quality which expired a while back in Janurary. 
![Screenshot_20220206-002525_Photos~2](https://user-images.githubusercontent.com/30292597/152668890-49ec0e2c-31cf-460f-a5bc-bcca0e797cc8.png)

![image](https://user-images.githubusercontent.com/30292597/152668905-ca9e4e26-24ca-42a9-8547-d1c7dd579b13.png)
https://support.google.com/photos/answer/6220791?hl=en&co=GENIE.Platform%3DAndroid#zippy=%2Coriginal-quality%2Cpixel

**Comment by Kingsman44** [comment]
yeah happended because P3 support dropped, but Its fixed!! , you will get via next update.

Fixed version is available in v2-beta-1 which can be found in Pixelify telegram group
Note: magisk v24+ required

**Comment by Kingsman44** [comment]
This should be fixed on pixelily v2

feel free to reopen or create new issue if doesn't

**Comment by gerardovasquez307** [comment]
Hi kingsman, I still have this issue on the latest Pixelify version on oxygen os 11 on Oneplus 9. I even put my phone in the freezer and photos still says phone too hot. I cleared photos data, play services and tried again with no luck. I have tried literally everything

**Comment by phenomdark27** [comment]
> I am also facing the same issue. Here is the workaround if anybody could try. working for me but still taking too much time. Note: My device feels cold. No actual heat up. Temp Solution: Put the device in front of the AC / in the freezer. Turn on App Pinning, Set the screen off timer to 30 minutes. Put Google photos as pinned App. Hope this works.
> 
> My device - Oneplus 6 on Oxegen 11 official ROM.

I tried this, not working for me, keeps on showing too hot!

Device : Oneplus 6 (LineageOS 19 - Android 12)

**Comment by gerardovasquez307** [comment]
Hi Kingsman,

Is there a way to hook onto the Google photos method that checks the temperature of the device and spoof temperature values? My theory is that Oneplus 9 SOC always runs hotter than the pixel's SOC range we are spoofing.

**Comment by phenomdark27** [comment]
I don't think it is a genuine temperature issue, because I kept my phone right in front of AC vent, yet it was giving the same error. I think this is a way of google telling us that the spoofing is not working somehow.
Also when it did work, the uploads were taking space from the 15 gb free storage.

**Comment by NightMean** [comment]
I experience the same on my Nothing Phone (1) but the photos do eventually backup during the night when the phone is not in use.

**Comment by NightMean** [comment]
To be honest @Pedrat I haven't experienced this for quite a while now. Could have been some Google Photos update that fixed it.

**Comment by Pedrat** [comment]
I see. That's odd then, I just got my Nothing and rooted it pretty much immediately with everything updated, so I'm guessing it either "gets used to it" or maybe there's something else causing it.

Either way, it doesn't annoy me much, as it still gets backed up anyway when I'm not using the phone, so no harm done there.

**Comment by milindpatel63** [comment]
I'm also having this issue. I'm running Pixelify 3.0 on Oneplus7Pro running latest Pixel Experience 14 beta.
