### ISSUE TITLE
Can't use Assistant Voice Type because it needs an update

### ISSUE THREAD

**Issue by ruvaldak** [Kingsman44/Pixelify#71]
Assistant Voice Typing says that it needs an update and to connect to Wi-Fi to automatically download it. I've had my phone on Wi-Fi, powered on, for about 2 days since flashing this module, and I still can't turn on Assistant Voice Typing. 

I'm using a Pixel 5 running ProtonAOSP 12.3.0 (Based on AOSP 12L).

**Comment by Kingsman44** [comment]
try manually download language pack of Google text to speech, and Google app

**Comment by ruvaldak** [comment]
How do I do that?

**Comment by Kingsman44** [comment]
Go to Google app > settings > voice > offline speech > Download lang pack.
also which lang you are trying for assistant voice typing? ENG or JP or DE?

**Comment by ruvaldak** [comment]
> Go to Google app > settings > voice > offline speech > Download lang pack. also which lang you are trying for assistant voice typing? ENG or JP or DE?

Just tried that, didn't work. ENG is what I use. I even downloaded every single English pack

**Comment by Kingsman44** [comment]
your issue is fixed?

**Comment by ruvaldak** [comment]
It seems so, for now at least. I wish I could use a newer version of the
Google app - The version I have to use (13.20.9.29) doesn't actually
support assistant on my Galaxy watch 4.

**Comment by islam-echo3ss39** [comment]
In Pixelify 2.2 I'm facing the same issue. Connected to a wifi but still doesn't work. I also tried clearing data and cache Google app and Gboard.

ROM: SparkOS 13.5 (A13)
